ALTER TABLE lots
  ADD COLUMN IF NOT EXISTS status_id INTEGER REFERENCES inventory_statuses(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS status_name TEXT,
  ADD COLUMN IF NOT EXISTS status_color TEXT;
